config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new"

  get "tasks/:id", to: "tasks#show", as: "show"

  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: "edit"

  patch "tasks/:id", to: "tasks#update", as: "task"

  delete "tasks/:id", to: "tasks#destroy", as: "destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <span>Completed</span>
  <%= f.submit %>
<% end %>

<!-- <form action="/tasks/3" method="patch">


</form> -->

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
  <!-- <p><%= task.title %></p> -->
  <% if task.completed == false %>
    <input type="checkbox" name="incomplete" disabled>
  <% else %>
    <input type="checkbox" name="complete" checked disabled>
  <% end %>
  <span><%= link_to task.title, show_path(task) %></span>
  <span><%= link_to "Delete", destroy_path(task), method: :delete %></span></br>
<% end %>



<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit "Create Task" %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<%= @task.details %>

<% if @task.completed == true %>
  <p>This task is completed</p>
<% else %>
  <p>This task is not completed yet</p>
<% end %>

<%= link_to "Back to list", tasks_path %>

<%= link_to "Edit this task", edit_path %>